name: Build Windows

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Test Files'
        required: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install modules.
        run: npm install --legacy-peer-deps
      - name: Build artifacts.
        run: npm run dist:win portable
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Upload EXE.
        uses: actions/upload-artifact@v3
        with:
          name: win-portable
          path: dist/Heroic*.exe
          retention-days: 14
