name: Build macOS

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Test Files'
        required: false

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install node-gyp.
        run: pnpm add --global node-gyp
      - name: Install modules.
        run: pnpm install --frozen-lockfile
      - name: Build artifacts.
        run: pnpm dist:mac --x64 --arm64 --publish=never
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
      - name: Upload x64.
        uses: actions/upload-artifact@v3
        with:
          name: mac-x64
          path: dist/Heroic*x64.dmg
          retention-days: 14
      - name: Upload ARM64.
        uses: actions/upload-artifact@v3
        with:
          name: mac-arm64
          path: dist/Heroic*arm64.dmg
          retention-days: 14
