name: Build Linux

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Test Files'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install snapcraft -y
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install node-gyp.
        run: pnpm add --global node-gyp
      - name: Install modules.
        run: pnpm install --frozen-lockfile
      - name: Build artifacts.
        run: pnpm dist:linux appimage snap --publish=never
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Upload AppImage.
        uses: actions/upload-artifact@v3
        with:
          name: linux-appimage
          path: dist/Heroic-*.AppImage
          retention-days: 14
      - name: Upload Snap.
        uses: actions/upload-artifact@v3
        with:
          name: linux-snap
          path: dist/*.snap
          retention-days: 14
