name: Lint

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install node-gyp.
        run: pnpm add --global node-gyp
      - name: Install modules.
        run: pnpm install --frozen-lockfile
      - name: Lint code.
        run: pnpm lint
      - name: Prettier code.
        run: pnpm prettier
      - name: Find dead code
        run: pnpm find-deadcode
