name: Test

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install node-gyp.
        run: pnpm add --global node-gyp
      - name: Install modules.
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test:ci
